# Generated by Django 2.1.2 on 2018-10-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='CRID',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='idea',
            name='owner',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
