# Generated by Django 2.1.2 on 2018-10-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_auto_20181025_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='id',
        ),
        migrations.AlterField(
            model_name='idea',
            name='CRID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
