# Generated by Django 2.1.2 on 2018-11-15 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_auto_20181025_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='CRIDStatus',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='bcStatus',
        ),
    ]
