from django.db import models


class User(models.Model):
    userid = models.CharField(max_length=100)
    token = models.CharField(max_length=100)

class Idea(models.Model):
  class1= models.CharField(max_length=100,blank=True)
  CRID= models.CharField(max_length=100)
  market= models.CharField(max_length=100,blank=True)
  plantCode= models.CharField(max_length=100,blank=True)
  model= models.CharField(max_length=100,blank=True)
  tvmCategory= models.CharField(max_length=100,blank=True)
  ideaType= models.CharField(max_length=100,blank=True)
  partNumber= models.CharField(max_length=100,blank=True)
  supplierGSDB= models.CharField(max_length=100,blank=True)
  description= models.CharField(max_length=100,blank=True)
  ChangeFrom= models.CharField(max_length=100,blank=True)
  changeTo= models.CharField(max_length=100,blank=True)
  ideaInDate= models.CharField(max_length=100,blank=True)
  bcDate= models.CharField(max_length=100,blank=True)
  leadFunction= models.CharField(max_length=100,blank=True)
  spoc= models.CharField(max_length=100,blank=True)
  ideaSource= models.CharField(max_length=100,blank=True)
  CRIDStage= models.CharField(max_length=100,blank=True)
  remark= models.CharField(max_length=100,blank=True)
  expImpDate= models.CharField(max_length=100,blank=True)
  weekShownOnImp= models.CharField(max_length=100,blank=True)
  weekShownForProj= models.CharField(max_length=100,blank=True)
  annualSavings= models.IntegerField(default=0,blank=True)
  calSaving= models.IntegerField(default=0,blank=True)
  carryOverSavings= models.CharField(max_length=100,blank=True)
  ageingDays= models.IntegerField(default=0,blank=True)
  rank= models.CharField(max_length=100,blank=True)
  GSR= models.CharField(max_length=100,blank=True)
  ideaGeneratedBy= models.CharField(max_length=100,blank=True)
  dateOfImp= models.CharField(max_length=100,blank=True)
  owner= models.CharField(max_length=100)
